steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_AR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_IMAGE_NAME}",
        ".",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_AR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_IMAGE_NAME}"]

  # Deploy service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      [
        "run",
        "services",
        "update",
        "${_SERVICE_NAME}",
        "--platform=managed",
        "--image=${_AR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_IMAGE_NAME}",
        "--region=${_DEPLOY_REGION}",
        "--quiet",
      ]
    entrypoint: gcloud
substitutions:
    _IMAGE_NAME: atv
    _SERVICE_NAME: atv
    _DEPLOY_REGION: us-central1
    _AR_HOSTNAME: us-central1-docker.pkg.dev