#!/usr/bin/env python
# Copyright 2024 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generates a narrated video with subtitles from news articles and images.

This is a standalone script which takes as input an article text in .txt
 format and pictures (each with the same prefix plus a number starting from 0).
It will generate a video out of the concatenated images and text summarization,
 along with narrated audio and srt subtitles.
Typical usage example:
"""

import argparse
import logging
import os
import sys
import uuid
from audio import subtitles_generation_step
from audio import text_to_speech_step
import pipeline
import storyboarding
import text
from text import summarize_text_step
from util import create_workdir_step
import vertexai
import video
import yaml

AUDIO_FILE_NAME = "2_readaloud.wav"

SRT_FILE_NAME = "3_subtitles.srt"

STORYBOARD_FILE_NAME = "4_storyboard.json"

OUTPUT_VIDEO_FILE_NAME = "5_withaudiovideo.mp4"

OUTPUT_AUDIO_FILE_NAME = "6_finalaudio.mp3"


class VideoGenerator:
  """Orchestrates the video generation process by managing various steps.

  This class encapsulates the logic for generating audio, creating a storyboard,
  and producing the final video output. It utilizes a `ScriptGenerator` for
  text processing and interacts with various pipeline steps for each stage of
  the video creation.
  """

  def __init__(
      self,
      script_generator: text.ScriptGenerator = text.ScriptGenerator(speakers=2),
  ):
    """Initializes the VideoGenerator.

    Args:
      script_generator: An instance of `text.ScriptGenerator` used for
        generating scripts from article content. Defaults to a ScriptGenerator
        configured for 2 speakers.
    """
    self.script_generator = script_generator

  def generate_audio_step(self, context: pipeline.VideoGenerationContext):
    """Generates audio and subtitles from the provided article content.

    Args:
      context: The `VideoGenerationContext` containing configuration and data
        for the audio generation process.
    """
    self.script_generator.language = context.language
    self.script_generator.speakers = 2 if context.multivoice else 1
    self.script_generator.multitext = context.multitext
    pipeline.Pipeline(
        steps=[
            create_workdir_step.CreateWorkdirStep(context),
            summarize_text_step.SummarizeTextStep(
                context.workdir, self.script_generator
            ),
            text_to_speech_step.TextToSpeechStep(context),
            subtitles_generation_step.SubtitlesGenerationStep(context),
        ]
    ).process(context.article_content)

  def generate_storyboard_step(
      self, context: pipeline.VideoGenerationContext
  ) -> storyboarding.Storyboard:
    """Creates a storyboard from images, audio, and subtitle information.

    If the audio and SRT files do not exist, this method will first trigger
    the `generate_audio_step`.

    Args:
      context: The `VideoGenerationContext` containing all necessary inputs like
        image paths, article content, and audio/SRT file locations.

    Returns:
      A `Storyboard` object representing the generated storyboard.
    """
    audio_file_path = os.path.join(context.workdir, AUDIO_FILE_NAME)
    srt_file_path = os.path.join(context.workdir, SRT_FILE_NAME)

    if not os.path.exists(audio_file_path) or not os.path.exists(srt_file_path):
      self.generate_audio_step(context)

    return storyboarding.create_storyboard_step(
        article_content=context.article_content,
        image_paths=context.image_paths,
        main_audio_path=audio_file_path,
        srt_path=srt_file_path,
        generate_text_overlays=not context.disable_text_overlays,
        splash_image=context.splash_image,
        output_file_path=os.path.join(context.workdir, STORYBOARD_FILE_NAME),
    )

  def generate_video_step(self, context: pipeline.VideoGenerationContext):
    """Generates the final video output from a storyboard.

    If a storyboard file exists, it's loaded; otherwise, it's generated by
    calling `generate_storyboard_step`.

    Args:
      context: The `VideoGenerationContext` providing access to the storyboard
        and output video configuration.
    """
    storyboard_file_path = os.path.join(context.workdir, STORYBOARD_FILE_NAME)
    if os.path.exists(storyboard_file_path):
      storyboard = storyboarding.load_storyboard(storyboard_file_path)
    else:
      storyboard = self.generate_storyboard_step(context)

    video.GenerateVideoFromImagesStep(
        output_audio_path=f"{context.workdir}/{OUTPUT_AUDIO_FILE_NAME}",
        output_video_path=f"{context.workdir}/{OUTPUT_VIDEO_FILE_NAME}",
        burn_in_subtitles=context.burn_in_subtitles,
    ).process(storyboard)


def _parse_args(args=sys.argv[1:]) -> argparse.Namespace:
  """Parses command-line arguments for the video generation script.

  Args:
    args: A list of command-line arguments. Defaults to sys.argv[1:].

  Returns:
    An argparse.Namespace object containing the parsed arguments.
  """
  parser = argparse.ArgumentParser()
  parser.add_argument(
      "--config",
      "-c",
      type=str,
      default="config.yml",
      help="Path to the configuration YAML file. Defaults to 'config.yml'.",
  )
  parser.add_argument(
      "--video_id",
      type=str,
      default=None,
      help=(
          "Unique ID for the generated video. If not provided, a UUID will be"
          " generated."
      ),
  )
  parser.add_argument(
      "--article_path",
      "-a",
      type=argparse.FileType("r"),
      required=True,
      help="Path to the article text file.",
  )
  parser.add_argument(
      "--image_dir",
      "-i",
      type=str,
      required=True,
      help="Path to the directory containing images.",
  )
  parser.add_argument(
      "--splash_image",
      type=str,
      required=False,
      help="File name of the splash image (do not include filename extension)",
  )
  parser.add_argument(
      "--disable_text_overlays",
      action="store_true",
      default=False,
      help="Disables text overlay generation.",
  )
  parser.add_argument(
      "--burn_in_subtitles",
      action="store_true",
      default=False,
      help="When provided, subtitles will be burned into the content.",
  )
  parser.add_argument(
      "--multi_voice",
      action="store_true",
      default=False,
      help=argparse.SUPPRESS,
  )
  parser.add_argument(
      "--multi_text",
      action="store_true",
      default=False,
      help="When provided, the video will summarize multiple articles.",
  )
  parser.add_argument(
      "--language",
      "-l",
      default="en-US",
      choices=["en-US", "en-GB", "fr-FR", "de-DE", "es-ES", "pt-BR"],
      help="The language for the output video. Defaults to 'en-US'.",
  )
  parser.add_argument(
      "--step",
      choices=["audio", "storyboard", "video"],
      default="video",
      help="Run a discrete step in the video generation flow.",
  )
  parser.add_argument(
      "--debug",
      "-d",
      action="store_true",
      default=False,
      help="Enable debug logging.",
  )
  return parser.parse_args(args)


def _get_config(config_file_name: str) -> dict[str, str]:
  with open(config_file_name, "r", encoding="utf-8") as config_file:
    return yaml.safe_load(config_file)


def _get_image_paths(image_dir: str) -> list[str]:
  image_extensions = (".jpg", ".jpeg", ".png", ".gif", ".bmp")
  if not image_dir.endswith(os.path.sep):
    image_dir += os.path.sep
  image_files = []
  for filename in os.listdir(image_dir):
    _, ext = os.path.splitext(filename)
    if ext.lower() in image_extensions:
      image_files.append(os.path.join(image_dir, filename))
  return image_files


def main(args=sys.argv[1:]):
  """Main entry point for the video generation script.

  Args:
    args: A list of command-line arguments. Defaults to sys.argv[1:].
  """
  parsed_args = _parse_args(args)
  if parsed_args.debug:
    logging.getLogger().setLevel(logging.DEBUG)

  context = pipeline.VideoGenerationContext(
      _get_config(parsed_args.config),
      request_params={
          "article_content": parsed_args.article_path.read(),
          "image_paths": _get_image_paths(parsed_args.image_dir),
          "splash_image": parsed_args.splash_image,
          "multivoice": parsed_args.multi_voice,
          "disable_text_overlays": parsed_args.disable_text_overlays,
          "burn_in_subtitles": parsed_args.burn_in_subtitles,
          "language": parsed_args.language,
          "multitext": parsed_args.multi_text,
      },
      video_id=parsed_args.video_id or str(uuid.uuid4()),
  )
  parsed_args.article_path.close()

  vertexai.init(project=context.gcp_project, location=context.gcp_location)

  video_generator = VideoGenerator()
  match parsed_args.step:
    case "audio":
      video_generator.generate_audio_step(context)
    case "storyboard":
      video_generator.generate_storyboard_step(context)
    case "video":
      video_generator.generate_video_step(context)


if __name__ == "__main__":
  main()
